twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
        stripe_publish_key: '%env(STRIPE_PUBLISH_KEY)%'
        stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

when@test:
    twig:
        strict_variables: true
