twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_5_layout.html.twig' ]
    globals:
        paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
        paypal_client_secret: '%env(PAYPAL_CLIENT_SECRET)%'

when@test:
    twig:
        strict_variables: true
